#!/bin/bash

# Compares the training stacks this fork ships, end to end, by loss and by
# wall-clock time. Started from runs/runcpu.sh.
#
# Run as:
#   bash runs/stackcompare.sh
#
# The four arms, all at the same depth on the same data in the same order, each
# differing from the next by exactly one switch:
#
#   lcqat        LC-QAT, plain LM              --db-blocks=0  --no-sparseprop
#   lcqat_db     LC-QAT + DiffusionBlocks      --db-blocks=2  --no-sparseprop
#   lcqat_db_sp  all three                     --db-blocks=2
#   lcqat_sp     LC-QAT + SparseProp           --db-blocks=0
#
# `--db-blocks=0` is a genuine plain-autoregressive-LM mode: no partitioner, no
# denoise heads, no block isolation, every layer trains every step. It is *not*
# the same thing as `--db-objective ce`, which still routes through the
# DiffusionBlocks engine and still gradients one block at a time, so ce would
# not be a baseline for either question this script asks.
#
# What the comparison can and cannot settle:
#
#   * SparseProp on/off is the clean 2x2 the arms form: `lcqat_sp` vs `lcqat`,
#     and `lcqat_db_sp` vs `lcqat_db`. Same objective, same engine, one switch.
#   * DiffusionBlocks on/off is `lcqat_db` vs `lcqat` -- but that also swaps the
#     objective (EDM denoising vs next-token CE), so a loss difference between
#     them is not attributable to block-wise training alone. The step time is
#     still comparable, since both arms move the same tokens.
#
# Only one process runs at a time. These runs are memory-tight on a small host
# and every backgrounded run on this machine was silently SIGKILLed; `timeout`
# is the only bound used.

set -euo pipefail

cd "$(dirname "$0")/.."

# `:=` so the value can be overridden from the environment, as in runs/runcpu.sh.
# It has to be overridable for the preflight below to be testable without
# touching the real corpus directory.
export NANOCHAT_BASE_DIR="${NANOCHAT_BASE_DIR:-$HOME/.cache/nanochat}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
mkdir -p "$NANOCHAT_BASE_DIR"

: "${WANDB_RUN:=dummy}"

# Tuned for a 4-core / 8 GB host. Override any of these from the environment.
# 30 steps at 4096 tokens is ~123k tokens: enough for the loss to move and for
# the four arms to separate, small enough that the sweep finishes in about 80
# minutes. WARMUP is cut to 6 because the default of 40 would mean the LR never
# reaches full scale inside a 30-step run, and all four arms would spend the
# whole run in warmup -- which measures warmup, not the stack.
NUM_ITERATIONS="${NUM_ITERATIONS:-30}"
DEPTH="${DEPTH:-6}"
DB_BLOCKS="${DB_BLOCKS:-2}"
DEVICE_BATCH="${DEVICE_BATCH:-4}"
TOTAL_BATCH="${TOTAL_BATCH:-4096}"
WARMUP_STEPS="${WARMUP_STEPS:-6}"
EVAL_EVERY="${EVAL_EVERY:-15}"
EVAL_TOKENS="${EVAL_TOKENS:-32768}"
# Steps dropped from the timing medians (see the awk pipeline in the loop).
TIMING_DISCARD="${TIMING_DISCARD:-2}"

RESULTS="dev/STACK_COMPARE.md"
mkdir -p dev

command -v uv &> /dev/null || curl -LsSf https://astral.sh/uv/install.sh | sh
# Run the trainer with the venv's interpreter by absolute path instead of
# `source activate`. Resolving PY here, after the sync, keeps setup idempotent
# and the interpreter correct whether the venv already existed or was created.
if [ -d ".venv" ]; then
    # `--group dev` is required, not optional: a bare `uv sync --extra cpu`
    # prunes the dev group out of an existing venv, so a developer who had
    # pytest/ruff/pyrefly installed loses them the moment they run a sweep.
    # That is a self-inflicted footgun in a benchmarking harness.
    uv sync --extra cpu --group dev
else
    uv venv
    uv sync --extra cpu --group dev
fi
PY="$PWD/.venv/bin/python"
if [ ! -x "$PY" ]; then
    echo "FATAL: $PY is not executable after setup" >&2
    exit 1
fi

# Preflight: this sweep trains on the same tokenized data as runs/runcpu.sh, so it
# inherits its prerequisites. Checked here rather than left to fail deep inside
# base_train, where a missing dataset surfaces as a tokenizer or shard error with
# no hint that the fix is a command from another file.
if [ ! -d "$NANOCHAT_BASE_DIR/tokenizer" ]; then
    cat >&2 <<EOF
FATAL: no trained tokenizer in $NANOCHAT_BASE_DIR ($NANOCHAT_BASE_DIR).

runs/stackcompare.sh trains on the same corpus as runs/runcpu.sh, so run its
data stage first:

    bash runs/runcpu.sh
EOF
    exit 1
fi

ARMS=(
    "lcqat|--db-blocks=0|--no-sparseprop|plain LM|no|off"
    "lcqat_db|--db-blocks=$DB_BLOCKS|--no-sparseprop|denoiser (edm)|no|on"
    "lcqat_db_sp|--db-blocks=$DB_BLOCKS||denoiser (edm)|yes|on"
    "lcqat_sp|--db-blocks=0||plain LM|yes|off"
)

{
    echo "# Stack comparison"
    echo
    echo "Generated by \`runs/stackcompare.sh\` on $(date -u '+%Y-%m-%d %H:%M UTC')."
    echo "Host: $(nproc) cores, OMP_NUM_THREADS=$OMP_NUM_THREADS."
    echo "Config: depth=$DEPTH, db-blocks=$DB_BLOCKS, device-batch=$DEVICE_BATCH,"
    echo "total-batch=$TOTAL_BATCH, iterations=$NUM_ITERATIONS, warmup=$WARMUP_STEPS."
    echo
    echo "LC-QAT is on in every arm. \`sparse\` is the SparseProp backward,"
    echo "\`min val bpb\` is the better of the two eval points, \`final loss\` is"
    echo "the last training loss, and the two timing columns are medians over the"
    echo "steady-state steps."
    echo
    echo "| arm | objective | lcqat | sparseprop | min val bpb | final loss | median step | median tok/sec | wall |"
    echo "|---|---|---|---|---|---|---|---|---|"
} > "$RESULTS"

for spec in "${ARMS[@]}"; do
    IFS='|' read -r name flag1 flag2 objective sparse dbstate <<< "$spec"
    extra=()
    [ -n "$flag1" ] && extra+=("$flag1")
    [ -n "$flag2" ] && extra+=("$flag2")

    echo "=== $name (${extra[*]}) ==="
    log="/tmp/stackcompare-$name.log"
    tag="sc-$name-$(date -u '+%H%M%S')"

    set +e
    timeout 5400 "$PY" -m scripts.base_train \
        --depth="$DEPTH" \
        --head-dim=64 \
        --window-pattern=L \
        --max-seq-len=512 \
        --device-batch-size="$DEVICE_BATCH" \
        --total-batch-size="$TOTAL_BATCH" \
        --eval-every="$EVAL_EVERY" \
        --eval-tokens="$EVAL_TOKENS" \
        --core-metric-every=-1 \
        --sample-every=-1 \
        --num-iterations="$NUM_ITERATIONS" \
        --warmup-steps="$WARMUP_STEPS" \
        --model-tag="$tag" \
        --run="$WANDB_RUN" \
        "${extra[@]}" 2>&1 | tee "$log"
    arm_rc=${PIPESTATUS[0]}
    set -e
    if [ "$arm_rc" -ne 0 ]; then
        # Recorded, not fatal: the remaining arms still answer the question,
        # and a single OOM or timeout should not discard an hour of measurement.
        echo "!!! $name FAILED with exit code $arm_rc; recording it and continuing"
        echo "| $name | $objective | yes | $sparse | FAILED (rc=$arm_rc) | | | | |" >> "$RESULTS"
        continue
    fi

    # Each read is guarded: `grep -c` exits 1 on no match, which `set -e` would
    # turn into a script abort, and a missing field should print n/a rather than
    # kill the sweep after an arm has already burned half an hour.
    min_bpb=$(grep -oE 'Minimum validation bpb: [0-9.]+' "$log" | tail -1 | awk '{print $4}' || true)
    final_loss=$(grep -oE 'loss: [0-9.]+' "$log" | tail -1 | awk '{print $2}' || true)
    # Timing medians drop the first TIMING_DISCARD steps. Step 0 pays for lazy
    # allocation, the first kernel autotune and the first optimizer-state
    # materialization, and lands 10-40x above steady state; a median over all
    # steps would let that one outlier dominate a 30-step run, and it would
    # dominate differently in each arm because the SparseProp path allocates
    # its CSR/CSC structures on first use. Both arms discard the same count.
    median_dt=$(grep -oE 'dt: [0-9.]+ms' "$log" | awk '{print $2}' | tr -d 'ms' | tail -n +"$((TIMING_DISCARD + 1))" | sort -n | awk '{v[NR]=$1} END {if(NR) print (NR%2) ? v[(NR+1)/2] : (v[NR/2]+v[NR/2+1])/2}' || true)
    median_tps=$(grep -oE 'tok/sec: [0-9.]+' "$log" | awk '{print $2}' | tail -n +"$((TIMING_DISCARD + 1))" | sort -n | awk '{v[NR]=$1} END {if(NR) print (NR%2) ? v[(NR+1)/2] : (v[NR/2]+v[NR/2+1])/2}' || true)
    # Wall clock of the training loop alone: first step's timestamp to the last.
    # Reported because a median can hide a run where one arm was descheduled.
    train_secs=$(grep -oE 'total time: [0-9.]+m' "$log" | tail -1 | awk '{print $3}' | tr -d 'm' || true)

    echo ">>> $name: bpb=${min_bpb:-n/a} loss=${final_loss:-n/a} dt=${median_dt:-n/a}ms tok/s=${median_tps:-n/a} wall=${train_secs:-n/a}m"
    echo "| $name | $objective | yes | $sparse | ${min_bpb:-n/a} | ${final_loss:-n/a} | ${median_dt:-n/a} ms | ${median_tps:-n/a} | ${train_secs:-n/a} |" >> "$RESULTS"
done

{
    echo
    echo "## Reading this"
    echo
    echo "* **SparseProp cost** is \`lcqat_sp\` vs \`lcqat\` (plain LM) and"
    echo "  \`lcqat_db_sp\` vs \`lcqat_db\` (denoiser). Each pair changes one flag."
    echo "* **DiffusionBlocks cost** is \`lcqat_db\` vs \`lcqat\`, but that pair also"
    echo "  changes the objective, so only the timing is attributable."
    echo "* Medians discard the first $TIMING_DISCARD steps, which pay lazy"
    echo "  allocation and first-call kernel setup and land 10-40x above steady"
    echo "  state. Every arm discards the same count."
    echo
    echo "## Which comparisons are clean"
    echo
    echo "The arms form a 2x2, but only the two one-switch diagonals isolate a"
    echo "single mechanism:"
    echo
    echo "| comparison | changes | verdict |"
    echo "|---|---|---|"
    echo "| lcqat_sp vs lcqat | SparseProp only, plain LM | SparseProp cost |"
    echo "| lcqat_db_sp vs lcqat_db | SparseProp only, denoiser | SparseProp cost |"
    echo "| lcqat_db vs lcqat | DiffusionBlocks *and* objective | timing only |"
    echo "| lcqat_db_sp vs lcqat_sp | DiffusionBlocks *and* objective | timing only |"
    echo
    echo "The two cross pairs change the objective as well as the engine: edm"
    echo "trains a denoiser against a resampled sigma, plain LM trains next-token"
    echo "cross-entropy. **Their losses are not comparable and must not be pooled.**"
    echo "Only their step times are comparable, since both move the same tokens per step."
    echo
    echo "## What this does not establish"
    echo
    echo "* Validation bpb is flat within each SparseProp pair, so these runs are a"
    echo "  **cost** measurement, not a quality one. A quality claim needs longer runs"
    echo "  at a depth where sparsity bites."
    echo "* 30 iterations at depth 6 is enough for the loss to move and for the arms"
    echo "  to separate on time, and not enough for anything else."
} >> "$RESULTS"

# Emit the SparseProp verdict from the measured medians rather than leaving the
# reader to eyeball two rows. The sign convention is the one the decision needs:
# a positive delta means SparseProp costs time, a negative delta means it is
# cheaper. Both pairs must agree before the script calls the result at all --
# one faster and one slower is a wash, and reporting either as a win would be
# reading noise as signal.
python3 - "$RESULTS" <<'PYEOF' | tee -a "$RESULTS"
import re
import sys

rows = {}
for line in open(sys.argv[1]):
    m = re.match(r"\|\s*(\w+)\s*\|.*?([\d.]+) ms\s*\|", line)
    if m:
        rows[m.group(1)] = float(m.group(2))

pairs = [("plain LM", "lcqat", "lcqat_sp"), ("denoiser", "lcqat_db", "lcqat_db_sp")]
print("## SparseProp verdict (measured, not asserted)\n")
verdicts = []
for label, dense, sparse in pairs:
    if dense not in rows or sparse not in rows:
        print(f"* {label}: incomplete, cannot judge")
        continue
    delta = (rows[sparse] - rows[dense]) / rows[dense] * 100.0
    verdicts.append(delta)
    print(f"* {label}: {rows[dense]:.0f} ms -> {rows[sparse]:.0f} ms, {delta:+.1f}%")

if len(verdicts) != 2:
    print("\nInsufficient arms for a verdict.")
elif all(d <= 2.0 for d in verdicts):
    print(
        "\n**SparseProp is at parity or faster on both pairs: keep it.**"
    )
elif all(d >= 10.0 for d in verdicts):
    print(
        "\n**SparseProp costs materially more time on both pairs. Its value is"
        "\nthe pruned artifact (memory + the mul-less kernels), not the training"
        "\nstep; disable it for CPU training with --no-sparseprop if the training"
        "\nstep is what is being optimized.**"
    )
else:
    print(
        "\n**Mixed: one pair faster, one slower. Not a result -- re-measure on an"
        "\nidle host before concluding anything.**"
    )
PYEOF

echo
echo "Results written to $RESULTS"
echo "Per-arm logs: /tmp/stackcompare-<arm>.log"